spring.datasource.url=jdbc:sqlserver://localhost;databaseName=InventarioDB;encrypt=true;trustServerCertificate=true

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080